"""add product category and popularity

Revision ID: 05522f6350a9
Revises: e7c398fc43a1
Create Date: 2026-08-18 06:20:06.045942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05522f6350a9'
down_revision: Union[str, Sequence[str], None] = 'e7c398fc43a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'products',
        sa.Column(
            'category',
            sa.String(length=100),
            nullable=True
        )
    )

    op.add_column(
        'products',
        sa.Column(
            'popularity',
            sa.Integer(),
            nullable=True
        )
    )

    # Give existing products safe default values
    op.execute(
        "UPDATE products SET category = 'general' WHERE category IS NULL"
    )

    op.execute(
        "UPDATE products SET popularity = 0 WHERE popularity IS NULL"
    )

    # Make the columns required after existing rows are populated
    op.alter_column(
        'products',
        'category',
        existing_type=sa.String(length=100),
        nullable=False
    )

    op.alter_column(
        'products',
        'popularity',
        existing_type=sa.Integer(),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'popularity')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
